---

- hosts: all

  gather_facts: false

  tasks:

    - name: "debug variable value media_sapcar"
      debug: msg="{{ media_sapcar}}"

    - name: "debug variable value package_retries_delay"
      debug: msg="{{ package_retries_delay}}"
      
      
    - name: "debug variable value nw_ci_instance_ciInstanceNumber"
      debug: msg="{{ nw_ci_instance_ciInstanceNumber}}"
      
      
    - name: "debug variable value nw_ci_instance_ascsInstanceNumber"
      debug: msg="{{ nw_ci_instance_ascsInstanceNumber}}"
