---

  - name: Check the remote host Hostname, Version, Distribution with UNAME

    gather_facts: false

    hosts: all

    tasks:

      - name: UNAME command 

        register: unameout

        command: "uname -a"


      - name: Display Output
        
        debug:
      
          var: unameout.stdout_lines
      
      - name: Download Tomcat
        
        get_url:
          url: "http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.1/bin/apache-tomcat-9.0.1.tar.gz"
          dest: "/tmp/apache-tomcat-9.0.1.tar.gz"
      
      - name: Create tomcat directory
        
        file:
        
          path: /home/damatya/programs/tomcat
 
          state: directory

      - name: Extract tomcat archive
        
        unarchive:
          
          src: /tmp/apache-tomcat-9.0.1.tar.gz
 
          dest: /home/damatya/programs/tomcat

          remote_src: yes
